---
- name: Building
  hosts: build
  become: yes

  roles:
    - build

  - name: Github clone
    git:
      repo: https://github.com/miladhub/calculator-servlet-example.git
      dest: /tmp/calculator-servlet-example/
      clone: yes
      
- name: Production
  hosts: prod
  become: yes

  roles:
    - prod