---
- name: Building
  hosts: build
  become: yes

  roles:
    - build
      
- name: Production
  hosts: prod
  become: yes

  roles:
    - prod

  tasks:
  - name: Move artifact from master to prod
    synchronize:
      mode: push
      src: /tmp/mycalcwebapp.war
      dest: dest_artifact
    notify:
      - Restart tomcat