---
# tasks file for prod
- name: Tomcat packages
  apt:
    name: tomcat9
    state: present

  - name: Move artifact from master to prod
    synchronize:
      mode: push
      src: /tmp/mycalcwebapp.war
      dest: dest_artifact
      notify:
        - Restart tomcat